[0m13:31:43.974123 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01e8e7b1c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01e73f88b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01e73f8910>]}


============================== 13:31:43.978221 | 023c04b3-1493-4464-a1df-bfb673a613cb ==============================
[0m13:31:43.978221 [info ] [MainThread]: Running with dbt=1.8.7
[0m13:31:43.978635 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:31:43.995996 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/root/.dbt')}
[0m13:31:43.996374 [info ] [MainThread]: Creating dbt configuration folder at 
[0m13:32:20.822282 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.10/dist-packages/dbt/include/starter_project
[0m13:32:20.836109 [info ] [MainThread]: 
Your new dbt project "isagri_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:32:20.836671 [info ] [MainThread]: Setting up your profile.
[0m13:35:17.665652 [info ] [MainThread]: Profile isagri_dbt written to /root/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:35:17.674258 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 213.75464, "process_user_time": 0.835098, "process_kernel_time": 0.378707, "process_mem_max_rss": "105888", "process_in_blocks": "36504", "process_out_blocks": "88"}
[0m13:35:17.675144 [debug] [MainThread]: Command `dbt init` succeeded at 13:35:17.674983 after 213.76 seconds
[0m13:35:17.675704 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01e8e7b1c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01e73da680>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01e73f89d0>]}
[0m13:35:17.676139 [debug] [MainThread]: Flushing usage events
[0m14:38:58.527274 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f10f154f130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f10efad7760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f10efad7700>]}


============================== 14:38:58.529255 | b94d3a5a-721a-4eb1-b9e2-e718c296acd3 ==============================
[0m14:38:58.529255 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:38:58.529607 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:39:24.152271 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.10/dist-packages/dbt/include/starter_project
[0m14:39:24.162665 [info ] [MainThread]: 
Your new dbt project "isagri_dbt_datateam" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:39:24.163123 [info ] [MainThread]: Setting up your profile.
[0m14:42:26.680951 [error] [MainThread]: Encountered an error:

[0m14:42:26.693709 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dbt/cli/main.py", line 470, in init
    results = task.run()
  File "/usr/local/lib/python3.10/dist-packages/dbt/task/init.py", line 347, in run
    self.setup_profile(profile_name)
  File "/usr/local/lib/python3.10/dist-packages/dbt/task/init.py", line 263, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/usr/local/lib/python3.10/dist-packages/dbt/task/init.py", line 180, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/usr/local/lib/python3.10/dist-packages/dbt/task/init.py", line 164, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/usr/local/lib/python3.10/dist-packages/dbt/task/init.py", line 130, in generate_target_from_input
    target[key] = click.prompt(
  File "/usr/local/lib/python3.10/dist-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/usr/local/lib/python3.10/dist-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m14:42:26.694555 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 208.2136, "process_user_time": 0.724998, "process_kernel_time": 0.059588, "process_mem_max_rss": "105916", "process_in_blocks": "600", "process_out_blocks": "80", "command_success": false}
[0m14:42:26.694978 [debug] [MainThread]: Command `dbt init` failed at 14:42:26.694904 after 208.21 seconds
[0m14:42:26.695239 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f10f154f130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f10ee704520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f10ee7055d0>]}
[0m14:42:26.695477 [debug] [MainThread]: Flushing usage events
[0m15:45:28.293769 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb231f530d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb2304d7880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb2304d7820>]}


============================== 15:45:28.296723 | 6e084457-d368-41eb-9e6b-df180e1f3d28 ==============================
[0m15:45:28.296723 [info ] [MainThread]: Running with dbt=1.8.7
[0m15:45:28.297177 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m15:45:28.297510 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/projects/ISAGRI-Airflow-AppInsights/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:45:28.298480 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.04575921, "process_user_time": 0.759675, "process_kernel_time": 0.109953, "process_mem_max_rss": "85060", "process_in_blocks": "280", "process_out_blocks": "16", "command_success": false}
[0m15:45:28.298834 [debug] [MainThread]: Command `dbt run` failed at 15:45:28.298769 after 0.05 seconds
[0m15:45:28.299051 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb231f530d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb2304d7910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb2304d7820>]}
[0m15:45:28.299284 [debug] [MainThread]: Flushing usage events
[0m14:29:20.495395 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3edc4fb220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3eda9e3b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3eda9e3ac0>]}


============================== 14:29:20.499986 | 1f1bf6ab-d71e-4f1b-90cc-50e0d218ca69 ==============================
[0m14:29:20.499986 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:29:20.500711 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:29:20.501032 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/projects/ISAGRI-Airflow-AppInsights/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:29:20.502002 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.048005782, "process_user_time": 0.782028, "process_kernel_time": 0.223436, "process_mem_max_rss": "84916", "process_in_blocks": "47304", "process_out_blocks": "8", "command_success": false}
[0m14:29:20.502368 [debug] [MainThread]: Command `dbt run` failed at 14:29:20.502299 after 0.05 seconds
[0m14:29:20.502589 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3edc4fb220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3eda9e3bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3eda9e3ac0>]}
[0m14:29:20.502810 [debug] [MainThread]: Flushing usage events
[0m16:47:54.413617 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca76c871c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca7521baf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca7521ba90>]}


============================== 16:47:54.415234 | 4bbd356d-e0d3-4b35-8277-f2310796a1cf ==============================
[0m16:47:54.415234 [info ] [MainThread]: Running with dbt=1.8.7
[0m16:47:54.415722 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run -s fct_orders', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:47:54.416009 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/projects/ISAGRI-Airflow-AppInsights/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:47:54.416532 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.052732605, "process_user_time": 0.689397, "process_kernel_time": 0.009991, "process_mem_max_rss": "84936", "process_in_blocks": "16", "process_out_blocks": "8", "command_success": false}
[0m16:47:54.416868 [debug] [MainThread]: Command `dbt run` failed at 16:47:54.416805 after 0.05 seconds
[0m16:47:54.417083 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca76c871c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca7521bb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca7521ba90>]}
[0m16:47:54.417292 [debug] [MainThread]: Flushing usage events
